ALTER TABLE providers ADD COLUMN max_concurrency INTEGER NOT NULL DEFAULT 0;
ALTER TABLE providers ADD COLUMN queue_timeout_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE providers ADD COLUMN max_queue_size INTEGER NOT NULL DEFAULT 100;
