// HTTP 状态码常量 — 全局唯一来源
export const HTTP_BAD_REQUEST = 400;
export const HTTP_CREATED = 201;
export const HTTP_FORBIDDEN = 403;
export const HTTP_NOT_FOUND = 404;
export const HTTP_CONFLICT = 409;
export const HTTP_INTERNAL_ERROR = 500;
export const HTTP_BAD_GATEWAY = 502;
export const HTTP_SERVICE_UNAVAILABLE = 503;
